
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS FLOAT ID INT STR\n    declaration : INT ID EQUALS INT\n               | FLOAT ID EQUALS FLOAT\n               | STR ID EQUALS STR\n    '
    
_lr_action_items = {'INT':([0,8,],[2,11,]),'FLOAT':([0,9,],[3,12,]),'STR':([0,10,],[4,13,]),'$end':([1,11,12,13,],[0,-1,-2,-3,]),'ID':([2,3,4,],[5,6,7,]),'EQUALS':([5,6,7,],[8,9,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> INT ID EQUALS INT','declaration',4,'p_declaration','Pruebas3.py',31),
  ('declaration -> FLOAT ID EQUALS FLOAT','declaration',4,'p_declaration','Pruebas3.py',32),
  ('declaration -> STR ID EQUALS STR','declaration',4,'p_declaration','Pruebas3.py',33),
]
