
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APERTUPAR CADENA CIERREPAR FIN FLOAT ID IF IGUAL INICIO INT NUM OPARIT OPRELAC PRINT STRINGPrograma : INICIO ID ListaInstrucciones FIN\n    ListaInstrucciones  : INSTRUCCION\n                        | ListaInstrucciones INSTRUCCION\n    \n    INSTRUCCION : ASIGNACION\n                | IFINSTR\n                | PRINTINSTR\n    \n    ASIGNACION : INT ID IGUAL EXPRESION\n                | STRING ID IGUAL CADENA\n                | FLOAT ID IGUAL EXPRESION\n    \n    EXPRESION   : NUM\n                | ID\n                | OPERACION\n    \n    OPERACION :  ID OPARIT ID\n              | ID OPARIT   NUM\n              | NUM OPARIT   NUM\n              | NUM OPARIT   ID\n\n\n    \n    IFINSTR : IF  CONDICION  INICIO ListaInstrucciones FIN\n    \n    CONDICION :  APERTUPAR EXPRESION OPRELAC EXPRESION CIERREPAR\n    \n    PRINTINSTR  : PRINT APERTUPAR CADENA CIERREPAR\n                | PRINT APERTUPAR EXPRESION   CIERREPAR\n    '
    
_lr_action_items = {'INICIO':([0,19,47,],[2,25,-18,]),'$end':([1,14,],[0,-1,]),'ID':([2,9,10,11,20,21,22,24,36,37,38,],[3,16,17,18,28,28,28,28,28,44,45,]),'INT':([3,4,5,6,7,8,15,25,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[9,9,-2,-4,-5,-6,-3,9,-10,-11,-12,-7,-8,-9,9,-19,-20,-17,-15,-16,-13,-14,]),'STRING':([3,4,5,6,7,8,15,25,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[10,10,-2,-4,-5,-6,-3,10,-10,-11,-12,-7,-8,-9,10,-19,-20,-17,-15,-16,-13,-14,]),'FLOAT':([3,4,5,6,7,8,15,25,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[11,11,-2,-4,-5,-6,-3,11,-10,-11,-12,-7,-8,-9,11,-19,-20,-17,-15,-16,-13,-14,]),'IF':([3,4,5,6,7,8,15,25,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[12,12,-2,-4,-5,-6,-3,12,-10,-11,-12,-7,-8,-9,12,-19,-20,-17,-15,-16,-13,-14,]),'PRINT':([3,4,5,6,7,8,15,25,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[13,13,-2,-4,-5,-6,-3,13,-10,-11,-12,-7,-8,-9,13,-19,-20,-17,-15,-16,-13,-14,]),'FIN':([4,5,6,7,8,15,27,28,29,32,33,34,35,39,40,41,43,44,45,46,],[14,-2,-4,-5,-6,-3,-10,-11,-12,-7,-8,-9,41,-19,-20,-17,-15,-16,-13,-14,]),'APERTUPAR':([12,13,],[20,21,]),'IGUAL':([16,17,18,],[22,23,24,]),'NUM':([20,21,22,24,36,37,38,],[27,27,27,27,27,43,46,]),'CADENA':([21,23,],[30,33,]),'OPRELAC':([26,27,28,29,43,44,45,46,],[36,-10,-11,-12,-15,-16,-13,-14,]),'CIERREPAR':([27,28,29,30,31,42,43,44,45,46,],[-10,-11,-12,39,40,47,-15,-16,-13,-14,]),'OPARIT':([27,28,],[37,38,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Programa':([0,],[1,]),'ListaInstrucciones':([3,25,],[4,35,]),'INSTRUCCION':([3,4,25,35,],[5,15,5,15,]),'ASIGNACION':([3,4,25,35,],[6,6,6,6,]),'IFINSTR':([3,4,25,35,],[7,7,7,7,]),'PRINTINSTR':([3,4,25,35,],[8,8,8,8,]),'CONDICION':([12,],[19,]),'EXPRESION':([20,21,22,24,36,],[26,31,32,34,42,]),'OPERACION':([20,21,22,24,36,],[29,29,29,29,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Programa","S'",1,None,None,None),
  ('Programa -> INICIO ID ListaInstrucciones FIN','Programa',4,'p_programa','Pruebas1.py',63),
  ('ListaInstrucciones -> INSTRUCCION','ListaInstrucciones',1,'p_ListaInstrucciones','Pruebas1.py',69),
  ('ListaInstrucciones -> ListaInstrucciones INSTRUCCION','ListaInstrucciones',2,'p_ListaInstrucciones','Pruebas1.py',70),
  ('INSTRUCCION -> ASIGNACION','INSTRUCCION',1,'p_INSTRUCCION','Pruebas1.py',76),
  ('INSTRUCCION -> IFINSTR','INSTRUCCION',1,'p_INSTRUCCION','Pruebas1.py',77),
  ('INSTRUCCION -> PRINTINSTR','INSTRUCCION',1,'p_INSTRUCCION','Pruebas1.py',78),
  ('ASIGNACION -> INT ID IGUAL EXPRESION','ASIGNACION',4,'p_ASIGNACION','Pruebas1.py',84),
  ('ASIGNACION -> STRING ID IGUAL CADENA','ASIGNACION',4,'p_ASIGNACION','Pruebas1.py',85),
  ('ASIGNACION -> FLOAT ID IGUAL EXPRESION','ASIGNACION',4,'p_ASIGNACION','Pruebas1.py',86),
  ('EXPRESION -> NUM','EXPRESION',1,'p_EXPRESION','Pruebas1.py',92),
  ('EXPRESION -> ID','EXPRESION',1,'p_EXPRESION','Pruebas1.py',93),
  ('EXPRESION -> OPERACION','EXPRESION',1,'p_EXPRESION','Pruebas1.py',94),
  ('OPERACION -> ID OPARIT ID','OPERACION',3,'p_OPERACION','Pruebas1.py',100),
  ('OPERACION -> ID OPARIT NUM','OPERACION',3,'p_OPERACION','Pruebas1.py',101),
  ('OPERACION -> NUM OPARIT NUM','OPERACION',3,'p_OPERACION','Pruebas1.py',102),
  ('OPERACION -> NUM OPARIT ID','OPERACION',3,'p_OPERACION','Pruebas1.py',103),
  ('IFINSTR -> IF CONDICION INICIO ListaInstrucciones FIN','IFINSTR',5,'p_IFINSTR','Pruebas1.py',111),
  ('CONDICION -> APERTUPAR EXPRESION OPRELAC EXPRESION CIERREPAR','CONDICION',5,'p_CONDICION','Pruebas1.py',117),
  ('PRINTINSTR -> PRINT APERTUPAR CADENA CIERREPAR','PRINTINSTR',4,'p_PRINTINSTR','Pruebas1.py',123),
  ('PRINTINSTR -> PRINT APERTUPAR EXPRESION CIERREPAR','PRINTINSTR',4,'p_PRINTINSTR','Pruebas1.py',124),
]
