
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APERTUPAR CADENA CIERREPAR FIN FLOAT ID IF IGUAL INICIO INT NUM OPARIT OPRELAC PRINT STRING WHILEPrograma : INICIO ID ListaInstrucciones FIN\n    ListaInstrucciones : INSTRUCCION\n                      | ListaInstrucciones INSTRUCCION\n    \n    INSTRUCCION : ASIGNACION\n                | IFINSTR\n                | WHILEINSTR\n                | PRINTINSTR\n    \n    ASIGNACION : INT ID IGUAL EXPRESION\n                | STRING ID IGUAL CADENA\n                | FLOAT ID IGUAL EXPRESION\n    \n    EXPRESION : NUM\n                       | ID\n                       | OPERACION\n    \n    OPERACION :  EXPRESION OPARIT EXPRESION\n    \n    IFINSTR : IF  CONDICION  APERTUPAR ListaInstrucciones CIERREPAR\n    \n    CONDICION :  APERTUPAR EXPRESION OPRELAC EXPRESION CIERREPAR\n    \n    WHILEINSTR : WHILE CONDICION APERTUPAR ListaInstrucciones CIERREPAR\n    \n    PRINTINSTR : PRINT APERTUPAR CADENA CIERREPAR\n                | PRINT APERTUPAR EXPRESION   CIERREPAR\n    '
    
_lr_action_items = {'INICIO':([0,],[2,]),'$end':([1,16,],[0,-1,]),'ID':([2,10,11,12,22,24,25,27,40,41,],[3,18,19,20,31,31,31,31,31,31,]),'INT':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[10,10,-2,-4,-5,-6,-7,-3,10,-11,-12,-13,10,-8,-9,-10,10,10,-18,-19,-15,-14,-17,]),'STRING':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[11,11,-2,-4,-5,-6,-7,-3,11,-11,-12,-13,11,-8,-9,-10,11,11,-18,-19,-15,-14,-17,]),'FLOAT':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[12,12,-2,-4,-5,-6,-7,-3,12,-11,-12,-13,12,-8,-9,-10,12,12,-18,-19,-15,-14,-17,]),'IF':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[13,13,-2,-4,-5,-6,-7,-3,13,-11,-12,-13,13,-8,-9,-10,13,13,-18,-19,-15,-14,-17,]),'WHILE':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[14,14,-2,-4,-5,-6,-7,-3,14,-11,-12,-13,14,-8,-9,-10,14,14,-18,-19,-15,-14,-17,]),'PRINT':([3,4,5,6,7,8,9,17,28,30,31,32,33,36,37,38,39,42,43,44,45,47,48,],[15,15,-2,-4,-5,-6,-7,-3,15,-11,-12,-13,15,-8,-9,-10,15,15,-18,-19,-15,-14,-17,]),'FIN':([4,5,6,7,8,9,17,30,31,32,36,37,38,43,44,45,47,48,],[16,-2,-4,-5,-6,-7,-3,-11,-12,-13,-8,-9,-10,-18,-19,-15,-14,-17,]),'CIERREPAR':([5,6,7,8,9,17,30,31,32,34,35,36,37,38,39,42,43,44,45,46,47,48,],[-2,-4,-5,-6,-7,-3,-11,-12,-13,43,44,-8,-9,-10,45,48,-18,-19,-15,49,-14,-17,]),'APERTUPAR':([13,14,15,21,23,49,],[22,22,24,28,33,-16,]),'IGUAL':([18,19,20,],[25,26,27,]),'NUM':([22,24,25,27,40,41,],[30,30,30,30,30,30,]),'CADENA':([24,26,],[34,37,]),'OPRELAC':([29,30,31,32,47,],[40,-11,-12,-13,-14,]),'OPARIT':([29,30,31,32,35,36,38,46,47,],[41,-11,-12,-13,41,41,41,41,41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Programa':([0,],[1,]),'ListaInstrucciones':([3,28,33,],[4,39,42,]),'INSTRUCCION':([3,4,28,33,39,42,],[5,17,5,5,17,17,]),'ASIGNACION':([3,4,28,33,39,42,],[6,6,6,6,6,6,]),'IFINSTR':([3,4,28,33,39,42,],[7,7,7,7,7,7,]),'WHILEINSTR':([3,4,28,33,39,42,],[8,8,8,8,8,8,]),'PRINTINSTR':([3,4,28,33,39,42,],[9,9,9,9,9,9,]),'CONDICION':([13,14,],[21,23,]),'EXPRESION':([22,24,25,27,40,41,],[29,35,36,38,46,47,]),'OPERACION':([22,24,25,27,40,41,],[32,32,32,32,32,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Programa","S'",1,None,None,None),
  ('Programa -> INICIO ID ListaInstrucciones FIN','Programa',4,'p_programa','Main.py',67),
  ('ListaInstrucciones -> INSTRUCCION','ListaInstrucciones',1,'p_ListaInstrucciones','Main.py',73),
  ('ListaInstrucciones -> ListaInstrucciones INSTRUCCION','ListaInstrucciones',2,'p_ListaInstrucciones','Main.py',74),
  ('INSTRUCCION -> ASIGNACION','INSTRUCCION',1,'p_INSTRUCCION','Main.py',80),
  ('INSTRUCCION -> IFINSTR','INSTRUCCION',1,'p_INSTRUCCION','Main.py',81),
  ('INSTRUCCION -> WHILEINSTR','INSTRUCCION',1,'p_INSTRUCCION','Main.py',82),
  ('INSTRUCCION -> PRINTINSTR','INSTRUCCION',1,'p_INSTRUCCION','Main.py',83),
  ('ASIGNACION -> INT ID IGUAL EXPRESION','ASIGNACION',4,'p_ASIGNACION','Main.py',89),
  ('ASIGNACION -> STRING ID IGUAL CADENA','ASIGNACION',4,'p_ASIGNACION','Main.py',90),
  ('ASIGNACION -> FLOAT ID IGUAL EXPRESION','ASIGNACION',4,'p_ASIGNACION','Main.py',91),
  ('EXPRESION -> NUM','EXPRESION',1,'p_EXPRESION','Main.py',97),
  ('EXPRESION -> ID','EXPRESION',1,'p_EXPRESION','Main.py',98),
  ('EXPRESION -> OPERACION','EXPRESION',1,'p_EXPRESION','Main.py',99),
  ('OPERACION -> EXPRESION OPARIT EXPRESION','OPERACION',3,'p_OPERACION','Main.py',105),
  ('IFINSTR -> IF CONDICION APERTUPAR ListaInstrucciones CIERREPAR','IFINSTR',5,'p_IFINSTR','Main.py',111),
  ('CONDICION -> APERTUPAR EXPRESION OPRELAC EXPRESION CIERREPAR','CONDICION',5,'p_CONDICION','Main.py',117),
  ('WHILEINSTR -> WHILE CONDICION APERTUPAR ListaInstrucciones CIERREPAR','WHILEINSTR',5,'p_WHILEINSTR','Main.py',123),
  ('PRINTINSTR -> PRINT APERTUPAR CADENA CIERREPAR','PRINTINSTR',4,'p_PRINTINSTR','Main.py',129),
  ('PRINTINSTR -> PRINT APERTUPAR EXPRESION CIERREPAR','PRINTINSTR',4,'p_PRINTINSTR','Main.py',130),
]
